import './styles.css'

const API_BASE = globalThis.SECUREMAILSCOPE_API_URL || `${window.location.protocol}//${window.location.hostname}:8000`
const MAX_UPLOAD_SIZE = 100 * 1024 * 1024
const state = { analysis: null, activeTab: 'overview', file: null, error: '', loading: false, health: 'checking', simulation: null }
const app = document.querySelector('#app')

const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character])
const formatBytes = (bytes) => { if (!bytes) return '0 B'; const units = ['B', 'KB', 'MB', 'GB']; const index = Math.floor(Math.log(bytes) / Math.log(1024)); return `${(bytes / 1024 ** index).toFixed(index ? 1 : 0)} ${units[index]}` }
const formatPercent = (value) => `${Math.round((Number(value) || 0) * 100)}%`
const severityClass = (value) => String(value || 'info').toLowerCase()
const api = async (path, options = {}) => { const response = await fetch(`${API_BASE}${path}`, options); if (!response.ok) { let detail = `Request failed (${response.status})`; try { detail = (await response.json()).detail || detail } catch {} throw new Error(detail) } return response.json() }

function renderShell(content = renderLanding()) {
  const analysis = state.analysis?.analysis
  app.innerHTML = `<div class="app-shell"><header class="topbar"><a class="brand" href="#"><span class="brand-mark">S</span><span>SecureMail<span class="brand-accent">Scope</span></span></a><div class="topbar-meta"><span class="version">${analysis ? escapeHtml(analysis.filename) : 'LOCAL FORENSICS'}</span><span class="api-status ${state.health}"><i></i>${state.health === 'online' ? 'API online' : state.health === 'offline' ? 'API offline' : 'Checking API'}</span></div></header>${content}<footer><span>SecureMailScope</span><span>Observed facts · local assessment · explainable signals</span></footer></div>`
  bindShellEvents()
}

function renderLanding() {
  return `<main class="landing"><section class="hero"><div class="hero-copy"><p class="eyebrow">Cryptographic forensic observatory</p><h1>Find the deviation hiding in your <em>mail traffic.</em></h1><p class="hero-text">Reconstruct email sessions, inspect TLS posture, and compare observed behavior against the local infrastructure baseline.</p></div><div class="hero-stamp"><span>01</span><span>capture<br>intake</span></div></section><section class="intake workspace"><div class="section-intro"><div><p class="eyebrow">Analysis workspace</p><h2>Start with a capture</h2></div><span class="step-count">REAL PCAP</span></div><form id="upload-form"><label class="drop-zone ${state.file ? 'has-file' : ''}" for="pcap-file" tabindex="0" role="button" aria-label="Choose a packet capture file"><input id="pcap-file" type="file" accept=".pcap,.pcapng,.cap" ${state.loading ? 'disabled' : ''}> <span class="drop-zone-icon">↓</span><span class="drop-zone-label">${state.file ? `<strong>${escapeHtml(state.file.name)}</strong><small>${formatBytes(state.file.size)}</small>` : 'Drop a packet capture here or <span>browse files</span>'}</span><span class="drop-zone-hint">PCAP, PCAPNG, or CAP · maximum 100 MB</span></label><div class="action-row"><div class="privacy-note"><span class="lock-icon">⌁</span><span>Files stay in your local analysis workspace.</span></div><button class="primary-button" type="submit" ${!state.file || state.loading ? 'disabled' : ''}>${state.loading ? 'Processing capture...' : 'Analyze capture'} <span>↗</span></button></div></form><button class="demo-button" id="demo-button" type="button">Load synthetic demo <span>SIMULATED DATA</span></button>${state.error ? `<div class="error-message" role="alert">${escapeHtml(state.error)}</div>` : ''}</section><section class="capabilities"><div class="capability-header"><p class="eyebrow">Forensic signal map</p><span>One pipeline · many lenses</span></div><div class="capability-grid"><article><span class="capability-number">01</span><h3>Session reconstruction</h3><p>SMTP, IMAP, POP3, TCP streams, STARTTLS transitions, and TLS evidence.</p></article><article><span class="capability-number">02</span><h3>Behavioral drift</h3><p>Compare each session to the cryptographic behavior observed for its server.</p></article><article><span class="capability-number">03</span><h3>Explainable risk</h3><p>Connect evidence to findings, confidence, impact, and remediation.</p></article></div></section></main>`
}

function renderDashboard() {
  const data = state.analysis
  const summary = data.summary
  const tabs = [['overview', 'Overview'], ['sessions', 'Sessions'], ['findings', 'Findings'], ['drift', 'Drift'], ['certificates', 'Certificates'], ['graph', 'Crypto graph'], ['reports', 'Reports']]
  return `<main class="dashboard"><section class="dashboard-head"><div><p class="eyebrow">${data.evidence.is_simulated ? 'SIMULATED DATA · NOT PACKET EVIDENCE' : 'REAL PCAP EVIDENCE'}</p><h1>${escapeHtml(data.analysis.filename)}</h1><p class="subtle">${escapeHtml(data.evidence.note || 'Tshark-backed passive analysis')} · ${escapeHtml(data.analysis.status)}</p></div><button class="outline-button" id="new-analysis">New analysis</button></section><nav class="tabs" aria-label="Analysis views">${tabs.map(([id, label]) => `<button class="tab ${state.activeTab === id ? 'active' : ''}" data-tab="${id}">${label}${id === 'findings' ? `<b>${data.findings.length}</b>` : ''}</button>`).join('')}</nav>${renderActiveView(data)}</main>`
}

function renderActiveView(data) {
  if (state.activeTab === 'sessions') return renderSessions(data)
  if (state.activeTab === 'findings') return renderFindings(data)
  if (state.activeTab === 'drift') return renderDrift(data)
  if (state.activeTab === 'certificates') return renderCertificates(data)
  if (state.activeTab === 'graph') return renderGraph(data)
  if (state.activeTab === 'reports') return renderReports(data)
  return renderOverview(data)
}

function metric(label, value, note = '') { return `<div class="metric"><span>${label}</span><strong>${value}</strong><small>${note}</small></div>` }
function renderOverview(data) {
  const s = data.summary
  const distributions = Object.entries(s.protocols || {}).map(([key, value]) => `<div class="bar-row"><span>${key}</span><i><b style="width:${s.total_sessions ? value / s.total_sessions * 100 : 0}%"></b></i><strong>${value}</strong></div>`).join('')
  const findings = data.findings.slice(0, 4).map(renderFindingRow).join('') || '<p class="empty">No findings observed.</p>'
  return `<section class="score-layout"><div class="score-panel"><p class="eyebrow">Security posture score</p><div class="score-value ${severityClass(s.risk_level)}">${s.risk_score}<small>/ 100</small></div><span class="risk-pill ${severityClass(s.risk_level)}">${s.risk_level}</span><p class="score-note">Application assessment model. This is not an external compliance standard.</p></div><div class="metric-grid">${metric('Total sessions', s.total_sessions, 'Reconstructed streams')}${metric('TLS sessions', s.tls_sessions, 'Handshake evidence')}${metric('Anomalous', s.anomalous_sessions, 'Local behavior model')}${metric('Critical / high', `${s.severity_counts.CRITICAL} / ${s.severity_counts.HIGH}`, 'Prioritized findings')}${metric('SMTP / IMAP / POP3', `${s.protocols.SMTP} / ${s.protocols.IMAP} / ${s.protocols.POP3}`, 'Detected protocols')}${metric('STARTTLS', s.starttls_sessions, 'Upgrade attempts')}</div></section><section class="overview-grid"><div class="panel"><div class="panel-head"><div><p class="eyebrow">Protocol distribution</p><h2>Observed sessions</h2></div><span>Evidence-backed</span></div>${distributions}</div><div class="panel"><div class="panel-head"><div><p class="eyebrow">Priority queue</p><h2>Top findings</h2></div><button class="text-button" data-tab="findings">View all ↗</button></div>${findings}</div></section><section class="panel"><div class="panel-head"><div><p class="eyebrow">What the model knows</p><h2>Evidence boundaries</h2></div></div><div class="limitation-grid">${(data.limitations || []).map((item) => `<p><span>i</span>${escapeHtml(item)}</p>`).join('') || '<p><span>✓</span>Fields shown are derived from the uploaded capture and local analysis pipeline.</p>'}</div></section>`
}

function renderFindingRow(finding) { return `<article class="finding-row"><span class="severity-dot ${severityClass(finding.severity)}"></span><div><strong>${escapeHtml(finding.title)}</strong><p>${escapeHtml(finding.description)}</p></div><span class="confidence">${formatPercent(finding.confidence)}</span></article>` }
function renderFindings(data) { return `<section class="view-head"><div><p class="eyebrow">Evidence-linked findings</p><h2>Prioritized security findings</h2></div><span>${data.findings.length} observations</span></section><section class="finding-list">${data.findings.length ? data.findings.sort((a, b) => severityRank(a.severity) - severityRank(b.severity)).map((finding) => `<article class="finding-card"><div class="finding-card-head"><span class="risk-pill ${severityClass(finding.severity)}">${finding.severity}</span><span class="finding-category">${finding.category}</span><span class="confidence">${formatPercent(finding.confidence)} confidence</span></div><h3>${escapeHtml(finding.title)}</h3><p>${escapeHtml(finding.description)}</p><div class="finding-meta"><span>Server <b>${escapeHtml(finding.affected_server || 'Not observed')}</b></span><span>Session <b>${finding.session_id ?? 'Not observed'}</b></span><span>Frames <b>${(finding.evidence_frames || []).join(', ') || 'Not observed'}</b></span></div><div class="recommendation"><span>Recommendation</span>${escapeHtml(finding.recommendation)}</div></article>`).join('') : '<p class="empty">No findings observed.</p>'}</section>` }
function severityRank(value) { return { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3, INFO: 4 }[value] ?? 5 }
function renderSessions(data) { return `<section class="view-head"><div><p class="eyebrow">Session explorer</p><h2>Reconstructed email sessions</h2></div><span>${data.sessions.length} streams</span></section><div class="table-wrap"><table><thead><tr><th>Protocol</th><th>Server</th><th>TLS</th><th>Cipher</th><th>Key exchange</th><th>Risk</th><th>Evidence</th></tr></thead><tbody>${data.sessions.map((session) => `<tr><td><span class="protocol-tag">${session.protocol}</span></td><td>${escapeHtml(session.server)}</td><td>${escapeHtml(session.tls_version || 'Not observed')}</td><td>${escapeHtml(session.cipher_suite || 'Not observed')}</td><td>${escapeHtml(session.key_exchange || 'Not observed')}</td><td><span class="risk-pill ${severityClass(session.risk_level)}">${session.risk_score} ${session.risk_level}</span></td><td>${(session.evidence_frames || []).join(', ')}</td></tr>`).join('')}</tbody></table></div>` }
function renderDrift(data) { return `<section class="view-head"><div><p class="eyebrow">Cryptographic forensic digital twin</p><h2>Baseline versus drift</h2></div><span>${data.baselines.length} server baselines</span></section><div class="drift-grid">${data.baselines.map((baseline) => `<article class="panel"><p class="eyebrow">${baseline.protocol} · ${baseline.server}</p><h3>${baseline.dominant_tls_version}</h3><p class="subtle">Dominant observed TLS version across ${baseline.total_sessions} sessions</p><div class="distribution">${Object.entries(baseline.tls_version_distribution).map(([key, value]) => `<div><span>${key}</span><strong>${value}</strong></div>`).join('')}</div></article>`).join('') || '<p class="empty">No baseline available. At least three sessions per server/protocol are required.</p>'}</div><section class="finding-list">${data.drift.map(renderFindingRow).join('') || '<p class="empty">No cryptographic drift observed.</p>'}</section>` }
function renderCertificates(data) { return `<section class="view-head"><div><p class="eyebrow">X.509 inventory</p><h2>Certificate posture</h2></div><span>${data.certificates.length} certificates</span></section><div class="certificate-grid">${data.certificates.map((certificate) => `<article class="panel certificate-card"><span class="certificate-state ${certificate.is_expired ? 'expired' : 'valid'}">${certificate.is_expired ? 'EXPIRED' : 'VALID'}</span><h3>${escapeHtml(certificate.subject || 'Not observed')}</h3><p>Issuer: ${escapeHtml(certificate.issuer || 'Not observed')}</p><div><span>Public key</span><strong>${escapeHtml(certificate.public_key_algorithm || 'Not observed')} ${certificate.public_key_size || ''}</strong></div><div><span>Signature</span><strong>${escapeHtml(certificate.signature_algorithm || 'Not observed')}</strong></div></article>`).join('') || '<p class="empty">No certificates extracted from this capture.</p>'}</div>` }
function renderGraph(data) { return `<section class="view-head"><div><p class="eyebrow">Cryptographic forensic digital twin</p><h2>Evidence relationship map</h2></div><span>Server → protocol → session → TLS</span></section><div class="graph"><div>Server</div><span>↓</span><div>Protocol</div><span>↓</span><div>Session</div><span>↓</span><div>TLS / cipher</div><span>↓</span><div>Certificate</div><span>↓</span><div>Finding</div></div><p class="graph-note">The map is a compact representation of the evidence chain. Select a session in the explorer to trace its frames and findings.</p>` }
function renderReports(data) { return `<section class="view-head"><div><p class="eyebrow">Forensic exports</p><h2>Reports and what-if controls</h2></div><span>Generated locally</span></section><div class="report-grid"><a class="report-link" href="${API_BASE}/api/analyses/${data.analysis.id}/report/json" target="_blank"><span>JSON</span><strong>Machine-readable evidence</strong><b>↗</b></a><a class="report-link" href="${API_BASE}/api/analyses/${data.analysis.id}/report/html" target="_blank"><span>HTML</span><strong>Shareable forensic brief</strong><b>↗</b></a><a class="report-link" href="${API_BASE}/api/analyses/${data.analysis.id}/report/pdf" target="_blank"><span>PDF</span><strong>Presentation-ready report</strong><b>↗</b></a></div><section class="panel simulator"><p class="eyebrow">Remediation simulator</p><h2>Test a safer posture</h2><p class="subtle">Simulation only. No mail server configuration will be changed.</p><div class="check-grid"><label><input type="checkbox" id="sim-tls"> Require TLS 1.2+</label><label><input type="checkbox" id="sim-cipher"> Disable legacy ciphers</label><label><input type="checkbox" id="sim-pfs"> Require forward secrecy</label><label><input type="checkbox" id="sim-cert"> Renew certificates</label></div><button class="primary-button" id="simulate-button" type="button">Simulate remediation ↗</button>${state.simulation ? `<div class="simulation-result"><strong>${state.simulation.current_risk_score} ${state.simulation.current_risk_level}</strong><span>→</span><strong>${state.simulation.projected_risk_score} ${state.simulation.projected_risk_level}</strong><p>${escapeHtml(state.simulation.note)}</p></div>` : ''}</section>` }

function bindShellEvents() { document.querySelector('#pcap-file')?.addEventListener('change', (event) => selectFile(event.target.files[0])); document.querySelector('#upload-form')?.addEventListener('submit', submitUpload); document.querySelector('#demo-button')?.addEventListener('click', loadDemo); document.querySelector('#new-analysis')?.addEventListener('click', () => { state.analysis = null; state.activeTab = 'overview'; renderShell() }); document.querySelectorAll('[data-tab]').forEach((element) => element.addEventListener('click', () => { state.activeTab = element.dataset.tab; renderShell(renderDashboard()) })); document.querySelector('#simulate-button')?.addEventListener('click', simulateRemediation); const zone = document.querySelector('.drop-zone'); zone?.addEventListener('dragover', (event) => { event.preventDefault(); zone.classList.add('is-dragging') }); zone?.addEventListener('dragleave', () => zone.classList.remove('is-dragging')); zone?.addEventListener('drop', (event) => { event.preventDefault(); zone.classList.remove('is-dragging'); selectFile(event.dataTransfer.files[0]) }); zone?.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); document.querySelector('#pcap-file')?.click() } }) }
function selectFile(file) { if (!file) return; state.error = ''; if (file.size > MAX_UPLOAD_SIZE) state.error = 'This file is larger than the 100 MB intake limit.'; else state.file = file; renderShell() }
async function submitUpload(event) { event.preventDefault(); if (!state.file || state.error) return; state.loading = true; renderShell(); const body = new FormData(); body.append('file', state.file); try { const receipt = await api('/api/analyze', { method: 'POST', body }); await pollAnalysis(receipt.analysis_id) } catch (error) { state.error = error.message; state.loading = false; renderShell() } }
async function pollAnalysis(id) { for (let attempt = 0; attempt < 120; attempt += 1) { const result = await api(`/api/analyses/${id}`); if (result.analysis.status === 'completed') { state.analysis = result; state.loading = false; renderShell(renderDashboard()); return } if (result.analysis.status === 'failed') throw new Error(result.analysis.error_message || 'Analysis failed.'); await new Promise((resolve) => setTimeout(resolve, 500)) } throw new Error('Analysis is taking longer than expected. Check the analysis history.') }
async function loadDemo() { state.loading = true; renderShell(); try { state.analysis = await api('/api/demo-analysis', { method: 'POST' }); state.loading = false; renderShell(renderDashboard()) } catch (error) { state.loading = false; state.error = error.message; renderShell() } }
async function simulateRemediation() { const changes = { require_tls12: document.querySelector('#sim-tls')?.checked, disable_legacy_ciphers: document.querySelector('#sim-cipher')?.checked, require_forward_secrecy: document.querySelector('#sim-pfs')?.checked, renew_certificates: document.querySelector('#sim-cert')?.checked }; try { state.simulation = await api(`/api/analyses/${state.analysis.analysis.id}/simulate-remediation`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(changes) }); renderShell(renderDashboard()) } catch (error) { state.error = error.message; renderShell(renderDashboard()) } }
async function checkHealth() { try { await api('/api/health'); state.health = 'online' } catch { state.health = 'offline' } if (!state.analysis) renderShell() }
renderShell(); checkHealth()
